project_id = "ckamflsosjzkyukajxzu"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.deduct-balance]
verify_jwt = false

[functions.create-deposit]
verify_jwt = false

[functions.sepay-webhook]
verify_jwt = false

[functions.purchase-vip]
verify_jwt = false

[functions.purchase-plan]
verify_jwt = false

[functions.purchase-vip-v2]
verify_jwt = false

[functions.assign-cookie]
verify_jwt = false

[functions.report-cookie]
verify_jwt = false

